#!/usr/bin/env python3
"""Moradin index refresher.

Walks memory/{principles,patterns,references,lessons}/, parses frontmatter,
writes _INDEX.md per subdir grouped by topic + writes top-level memory/_INDEX.md.

License: MIT
"""

import re
from collections import defaultdict
from pathlib import Path

MORADIN_ROOT = Path(__file__).resolve().parent.parent
MEMORY_ROOT = MORADIN_ROOT / "memory"

SUBDIRS = ["principles", "patterns", "references", "lessons"]

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)", re.DOTALL)


def parse_frontmatter(content):
    match = FRONTMATTER_RE.match(content)
    if not match:
        return {}
    fm_text = match.group(1)
    metadata = {}
    for line in fm_text.split("\n"):
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k = k.strip()
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            v = [x.strip().strip('"').strip("'") for x in v[1:-1].split(",") if x.strip()]
        metadata[k] = v
    return metadata


def gather_files(subdir):
    """Returns list of {name, path, description, topics, applies_to}."""
    dir_path = MEMORY_ROOT / subdir
    if not dir_path.exists():
        return []
    files = []
    for md_file in dir_path.glob("*.md"):
        if md_file.name.startswith("_"):
            continue
        try:
            content = md_file.read_text(encoding="utf-8")
        except Exception:
            continue
        metadata = parse_frontmatter(content)
        topics = metadata.get("topics", [])
        if isinstance(topics, str):
            topics = [topics]
        applies_to = metadata.get("applies_to", [])
        if isinstance(applies_to, str):
            applies_to = [applies_to]
        files.append({
            "name": md_file.name,
            "description": metadata.get("description", "(no description)"),
            "topics": topics,
            "applies_to": applies_to,
        })
    return files


def write_subdir_index(subdir, files):
    """Write memory/<subdir>/_INDEX.md grouped by topic."""
    dir_path = MEMORY_ROOT / subdir
    by_topic = defaultdict(list)
    for f in files:
        if not f["topics"]:
            by_topic["(untagged)"].append(f)
        else:
            for topic in f["topics"]:
                by_topic[topic].append(f)

    lines = [
        f"# {subdir.capitalize()} index",
        "",
        f"_Auto-generated by `scripts/refresh_indexes.py`. Do not edit by hand._",
        "",
        f"**Total files:** {len(files)}",
        "",
    ]
    for topic in sorted(by_topic.keys()):
        lines.append(f"## {topic}")
        lines.append("")
        for f in sorted(by_topic[topic], key=lambda x: x["name"]):
            applies = ", ".join(f["applies_to"]) or "—"
            lines.append(f"- **`{f['name']}`** ({applies}) — {f['description']}")
        lines.append("")

    (dir_path / "_INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def write_top_index(all_files_by_subdir):
    """Write memory/_INDEX.md as a catalog of all subdirs."""
    lines = [
        "# Memory index",
        "",
        "_Auto-generated by `scripts/refresh_indexes.py`._",
        "",
    ]
    total = sum(len(v) for v in all_files_by_subdir.values())
    lines.append(f"**Total memory files:** {total}")
    lines.append("")
    for subdir in SUBDIRS:
        files = all_files_by_subdir.get(subdir, [])
        lines.append(f"## {subdir} ({len(files)})")
        lines.append(f"See [`{subdir}/_INDEX.md`](./{subdir}/_INDEX.md) for catalog.")
        lines.append("")

    (MEMORY_ROOT / "_INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def main():
    if not MEMORY_ROOT.exists():
        print(f"No memory dir found at {MEMORY_ROOT}")
        return

    all_files = {}
    for subdir in SUBDIRS:
        files = gather_files(subdir)
        all_files[subdir] = files
        write_subdir_index(subdir, files)
        print(f"  {subdir}/_INDEX.md: {len(files)} files")

    write_top_index(all_files)
    total = sum(len(v) for v in all_files.values())
    print(f"\nmemory/_INDEX.md: {total} total files indexed")


if __name__ == "__main__":
    main()
